#!/usr/bin/bash
waybar -c $HOME/.config/hypr/component/waybar/config2 -s $HOME/.config/hypr/component/waybar/style2.css &
#waybar -c $HOME/.config/hypr/component/waybar/config -s $HOME/.config/hypr/component/waybar/style.css &
